services:
  api_gateway :
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT = 3000
  users_microservices :
    build: ./user-microservices
    volumes:
      - ./user-microservices/src:/usr/src/app/src
    command: npm run start:dev
  payments_microservices:
    build: ./user-microservices
    volumes:
      - ./payments-microservices/src:/usr/src/app/src
    command: npm run start:dev
  nats :
     image: nats
     ports:
       - 4222:4222
  mysql_db :
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=white_rose_102024
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3306

